base_view: omni_dbt__stg_order_items
label: dbt Jaffle Shop Order Items

joins:
  omni_dbt__stg_orders: {}
  omni_dbt__stg_products: {}
  omni_dbt__stg_supplies: {}

views:
  omni_dbt__stg_orders:
    label: Orders

  omni_dbt__stg_products:
    label: Products

  omni_dbt__stg_supplies:
    label: Supplies

  omni_dbt__stg_order_items:
    label: Order Items
